### ISSUE TITLE
Increased Boop.exe size.

### ISSUE THREAD

**Issue by miltoncandelero** [miltoncandelero/Boop#12]
Ehhmmm guys?

We went from 790kb to 6.82mb

What did I do?

Might it be the json.net library? Is there another library we should use?

**Comment by LeoLamCY** [comment]
One of the images added (IP.png) is 3.87 MB, might wanna compress it.

**Comment by miltoncandelero** [comment]
🤦‍♂️ 

Thanks. Fixed
