### ISSUE TITLE
Migrate the HTTP Server to TCPListener

### ISSUE THREAD

**Issue by miltoncandelero** [miltoncandelero/Boop#16]
All the crashes are due to using HTTPListener instead of TCPListener.

I'll try to make an TCPListener implementation of an httpserver. If someone on the internet knows how to do such thing, please become a friend of the snek.

*HTTPListener MUST BE STOPPED! The lives of the sneks depend on it!*

**Comment by SubstituteCS** [comment]
I will try, C# isn't my primary language, but I have written basic TCPListeners before.  I will write it as a module that you can include so that bug reports can be made separately.

**Comment by miltoncandelero** [comment]
Maybe this can help?

https://www.codeproject.com/articles/17071/sample-http-server-skeleton-in-c
