### ISSUE TITLE
Not working on latest FBI 2.4.6

### ISSUE THREAD

**Issue by xXAquaNightXx** [miltoncandelero/Boop#17]
FBI is just blank after i select install then i get the error

![20170102_192928](https://cloud.githubusercontent.com/assets/24309423/21597605/962a581e-d123-11e6-80b1-1020003ecc3b.jpg)

![20170102_193029](https://cloud.githubusercontent.com/assets/24309423/21597640/0b269db2-d124-11e6-8278-281c4cbda826.jpg)

**Comment by miltoncandelero** [comment]
It is working for me.

That error usually means your firewall is blocking the connection.

Did you allow the file when the firewall popup asked you to?

**Comment by xXAquaNightXx** [comment]
Ok you can close this now i tried another pc and it worked, thank you for the help
