### ISSUE TITLE
404 on served files containing "+"

### ISSUE THREAD

**Issue by Koopzington** [miltoncandelero/Boop#19]
First of all thanks for this extremely useful tool! I can't imagine live anymore without snek helping me out! :D

While serving some files i had one .cia file which had a "+" in it's filename and FBI displayed a 404 message.
Is that even fixable on your side or who is to blame for this? :D

**Comment by miltoncandelero** [comment]
Hello dear friend of the snek.

That's an interesting interaction.

I will look into it.
