### ISSUE TITLE
It's not booping...

### ISSUE THREAD

**Issue by CookieXD** [miltoncandelero/Boop#32]
Boop 1.4.0 itself doesn't shows any error, but FBI 2.4.12 does:
![boop](https://user-images.githubusercontent.com/14136885/32780622-4bee5058-c942-11e7-8fec-e04f6e5f08f7.png)

After FBI shows this error message, Boop tells me:" Yay! Booping complete! "

I am using an Windows 10 machine with outdated hardware and broken Taskbar+WindowsApps.
I am using an new 3ds with LumaCFW 8.1.1 Mod by [kasai07](https://github.com/kasai07/Luma3DS) with [Boot9strap](https://github.com/SciresM/boot9strap/releases) 1.3 the lastest version of FBI.

Hopefully it will be fixed...

**Comment by CCF100** [comment]
I know this isn't helpful, but how did you get the custom font?

**Comment by CookieXD** [comment]
I searched in google for:  3ds fonts cia
downloaded some and installed one.

**Comment by CookieXD** [comment]
Seems like it was a problem with the windows 10 firewall...
fixed it! Any workarounds yet?

**Comment by miltoncandelero** [comment]
Well. Disable your firewall seems a good workaround

Any other workaround of a firewall on my side of things would be malware.
