### ISSUE TITLE
Not works on FBI 2.5.0

### ISSUE THREAD

**Issue by mlcaamano** [miltoncandelero/Boop#35]
Stop worked on fbi version 2.5.0

**Comment by FAUXTIER** [comment]
Hello. I'm also having issues in this matter, but I noticed that only .cia bigger than 500MB is getting timeout error.

**Comment by miltoncandelero** [comment]
Apparently it was a fbi issue.

on 2.5.2 it said
> Fix URL installation.

I tried heavy files and had no problems. Closing.
