### ISSUE TITLE
Sometimes autodetect 3DS IP or manually writing the 3DS IP does not work

### ISSUE THREAD

**Issue by pitrako** [miltoncandelero/Boop#36]
Sometimes boop doesn't work even after writting the IP adress manually, I have to try various times:

![](https://image.ibb.co/cx2r89/Sin_t_tulo2.png)

![](https://image.ibb.co/ePdZvp/Sin_t_tulo.png)

**Comment by pun-pun** [comment]
Similar issue when using FTP to connect. You have to try numerous times. I think this is normal in this case too.

**Comment by miltoncandelero** [comment]
Now "detecting the console" isn't an option you pick but a guess the program makes. If it detected a nintendo MAC on the network it will pick it as default. You can then write your own if this resuts incorrect.
