### ISSUE TITLE
Error Windows 7

### ISSUE THREAD

**Issue by tsuihak** [miltoncandelero/Boop#49]
When you click BOOP the following error occurs:
Getting error "Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'"

**Comment by tsuihak** [comment]
I solved my problem by installing Net Framework 4.8, follow the link from where I downloaded it.
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by IsseiYoshida** [comment]
thx for reporte and solved
