### ISSUE TITLE
[Suggestion] Enable "Open with..." as shortcut

### ISSUE THREAD

**Issue by Mic1604** [miltoncandelero/Boop#8]
Enable the .exe to be targeted as a program to open .CIA files with, either prompting the user for an IP address or giving the option to use the last target.

This feature could be improved further by using network device pooling to detect Nintendo devices in the visible network and listing them as targets, while future-proofing in case Wii U .wup/.wumad/etc. network installation is ever made available.

**Comment by miltoncandelero** [comment]
mmm while doable the .cia and .tik association would need the .exe file to stay in one folder of your hard drive (installed). Could be done but I was going for a more "single exe, have it wherever you want and it works" approach. Still will look into the posibility of adding that functionality as optional.

The network scan is a huge feature. I'll look into it.
